version: '3.9'

services:
  nginx:
    container_name: core-nginx
    restart: unless-stopped
    build:
      context: ..
      dockerfile: deployment/nginx/nginx.Dockerfile
    environment:
      DOMAIN_NAME: "${DOMAIN_NAME}"
      PROTOCOL: "${SITE_PROTOCOL}"
    depends_on:
      - backend
      - secure
    volumes:
      - ./plugins/web:/data/plugins
      - ./nginx/mainframe-config.json:/input/mainframe-config.json
    ports:
      - '80:80'
    networks:
      - public

  backend:
    container_name: core-backend
    restart: unless-stopped
    build:
      context: ..
      dockerfile: deployment/backend.Dockerfile
    environment:
      RSA__public-key: "${RSA_PUBLIC_KEY_FILE}"
    depends_on:
      - backend-database
    volumes:
      - ./plugins/backend:/app/plugins
      - ./public-keys:/app/keys
    networks:
      - public
      - backend

  backend-database:
    container_name: core-backend-database
    restart: unless-stopped
    image: mariadb:10.10
    environment:
      MARIADB_ROOT_PASSWORD: network-security
    networks:
      - backend

  secure:
    container_name: core-secure
    restart: unless-stopped
    build:
      context: ..
      dockerfile: deployment/backend.secure.Dockerfile
    environment:
      ConnectionStrings__Production: "server=secure-database;database=core;user=root;password=network-security"
      MainframeOrigin: "${SITE_PROTOCOL}://mainframe.${DOMAIN_NAME}"
      LDAPConfiguration__ServerIp: "${LDAP_SERVER_IP}"
      JWT__Issuer: "${SITE_PROTOCOL}://mainframe.${DOMAIN_NAME}"
      JWT__Audience: "${SITE_PROTOCOL}://mainframe.${DOMAIN_NAME}"
      RSA__private-key: "${RSA_PRIVATE_KEY_FILE}"
      RSA__public-key: "${RSA_PUBLIC_KEY_FILE}"
    depends_on:
      - secure-database
    volumes:
      - ./private-keys:/app/keys
    networks:
      - public
      - secure

  secure-database:
    container_name: core-secure-database
    restart: unless-stopped
    image: mariadb:10.9
    environment:
      MARIADB_ROOT_PASSWORD: network-security
    networks:
      - secure

networks:
  public:
  backend:
  secure:
